class Specific_Prescribers():
    def __init__(self):
        self.pres_data2 = {
            'makar, gamil': ['gamilmakar1','1December!', None, None, 'Azeem', '(833) 664-4645','gamilmakar010@outlook.com','https://hook.us1.make.com/cp1obj67e3zk3oinnmuapc41xfuu2kk1',None,None,None,'07013', '11makarrrpt', 'Prescriber Specific - a'],
            'kremen, inna': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - 1'],
            'gupta, manjari': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - 2'],
            'owunna, uzoma': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - 3'],
            'gross, renee': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - 4'],
            'gleason, abigail': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - 5'],
            'brown, jennifer': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - 6'],

        }
        self.pres_data = {
            'makar, gamil': ['gamilmakar1','1December!', None, None, 'Azeem', '(833) 664-4645','gamilmakar010@outlook.com','https://hook.us1.make.com/cp1obj67e3zk3oinnmuapc41xfuu2kk1',None,None,None,'07013', '11makarrrpt', 'Prescriber Specific - a'],
            'majid, saniea': ['sanieamajidb','1December!', 'Sanieamajidb@gmail.com', 'rvkt jtor wyly rghm', 'Azeem', '(855) 535-0291',None,None,None,None,None,'07081', 'BFVzVcwSMG', 'Prescriber Specific - b'],
            'dresdner, michael': ['michaeldresdnerb','1December!', 'Michaeldresdnerb@gmail.com', 'wljz ivcc ixtm oqpy', 'Azeem', '(855) 486-6183',None,None,None,None,None,'07071', 'M47zqFf165', 'Prescriber Specific - c'],
            'denoble, shaghayegh': ['shaghayeghdenobleb','1December!', 'Shaghayeghdenobleb@gmail.com', 'qxtg zyyq kdfk axth', 'Azeem', '(855) 409-7564',None,None,None,None,None,'07450', 'j1DKUrC5l0', 'Prescriber Specific - d'],
            'hainer, meg': ['meghainerb','1December!', 'Meghainerb@gmail.com', 'sqxh fsmj uoqa hsid', 'Azeem', '(855) 264-3649',None,None,None,None,None,'60098', 'lOZS5tlm9l', 'Prescriber Specific - e'],
            'barness, michael': ['michaelbarnessbar','1December!', 'michaelbarnessbar@gmail.com', 'xatj hglt vhis jvnu', 'Azeem', '(855) 357-6295',None,None,None,None,None,'07078', 'H3YZbY6UUr', 'Prescriber Specific - f'],
            'mazzoccoli, vito': ['Premfammed','Family51!', 'Premfammed@gmail.com', 'kwlg pjub gbmv vqhu', 'Azeem', '(973) 695-1684',None,None,None,None,None,'07005', 'ZfOQ9mJ2m6', 'Prescriber Specific - g'],
            'saitta, jacqueline': ['Jacquelinesaittacr','1December!', 'Jacquelinesaittacr@gmail.com', 'ltbc jcvd jbmr futw', 'Azeem', '(855) 513-7089',None,None,None,None,None,'07052', 'qGqurAAV4U', 'Prescriber Specific - h'],
            'zhang, yuqing': ['yuqingzhang','1December!', 'yuqingzhangsc@gmail.com', 'rohu nzyd ibys bzbf', 'Azeem', '(855) 486-6188',None,None,None,None,None,'11354', '4pcdtgE32G', 'Prescriber Specific - i'],
            'shen, angela': ['angelashensc','1December!', 'angelashensc@gmail.com', 'umra yati aihj njdr', 'Azeem', '(855) 491-5804',None,None,None,None,None,'10023', '7n7sifqMdO', 'Prescriber Specific - j'],
            'zhou, jin': ['jinzhousc','1December!', 'jinzhousc@gmail.com', 'vgqp xcio lhou dhgp', 'Azeem', '(855) 560-1624',None,None,None,None,None,'11355', 'XhN212hJjB', 'Prescriber Specific - k'],
            'cao, ning': ['ningcaosc','1December!', 'ningcaosc@gmail.com', 'oklr ffje pdea fljt', 'Azeem', '(855) 556-7283',None,None,None,None,None,'11358', 'W2s2axxF6F', 'Prescriber Specific - l'],
            'chan, sing': ['singchanscare','1December!', 'singchanscare@gmail.com', 'jjvx lphe erff zskp', 'Azeem', '(855) 603-3214',None,None,None,None,None,'11354', '0YQQFtOyh8', 'Prescriber Specific - m'],
            'khan, saima': ['saimakhancli','1December!', 'saimakhancli@gmail.com', 'dzrj jzag enfx ucie', 'Azeem', '(855) 598-2612',None,None,None,None,None,'49008', 'zVWlAcZyWw', 'Prescriber Specific - n'],
            'fox, alissa b': ['alissafoxc','1December!', 'alissafoxc@gmail.com', 'rjsf pktx vypm mpys', 'Azeem', '(855) 566-4458',None,None,None,None,None,'08876', 'Blu1fiDeGK', 'Prescriber Specific - o'],
            'ferrara, elizabeth': ['elizabethferrarac','1December!', 'elizabethferrarac@gmail.com', 'vckq enju mfxb qupw', 'Azeem', '(855) 546-5460',None,None,None,None,None,'19114', 'TDbux1r750', 'Prescriber Specific - p'],
            'mian, bilal': ['mianbilalcli','1December!', 'mianbilalcli@gmail.com', 'juoc ezyy tkrc ahuu', 'Azeem', '(833) 619-1228',None,None,None,None,None,'45504', '909LLSikRH', 'Prescriber Specific - q'],
            'rivas, jimena': ['jimenarivascli','1December!', 'jimenarivascli@gmail.com', 'kwhs mymc ubra gbhi', 'Azeem', '(855) 514-6216',None,None,None,None,None,'08822', 'e6iPY94zNl', 'Prescriber Specific - r'],
            'calderon, rosa': ['calderonrosain','1December!', 'calderonrosain@gmail.com', 'nwlg wnvm csfu ewhq', 'Azeem', '(833) 664-4542',None,None,None,None,None,'07087', 'xPyL0BZsA4', 'Prescriber Specific - s'],
            'onyeador o, beatrice': ['beatriceonyeadorint','1December!', 'beatriceonyeadorint@gmail.com', 'txzo viuc gvgb wiue', 'Azeem', '(833) 689-1577',None,None,None,None,None,'07011', 'qzhBnXbSGy', 'Prescriber Specific - t'],
            'revoredo, fred': ['fredrevoredoint','1December!', 'fredrevoredoint@gmail.com', 'laqk uwxu qjos gsac', 'Azeem', '(833) 664-4413',None,None,None,None,None,'07504', '7WWYOPJ45p', 'Prescriber Specific - u'],
            'marani dicovski, marcela': ['marcelamerani','1December!', 'marcelameraniint@gmail.com', 'ayys scvd hbmr ebkq', 'Azeem', '(833) 940-2179',None,None,None,None,None,'07514', '5lS7p4avJ2', 'Prescriber Specific - v'],
            'agrawala, ajay': ['ajayagarwalamy','1December!', 'ajayagarwalamy@gmail.com', 'efhb jqbp baph ntfv', 'Azeem', '(855) 587-7417',None,None,None,None,None,'07080', '3B0zuq2zFO', 'Prescriber Specific - w'],
            'shah, sulay': ['Sulayshahmy','1December!', 'Sulayshahmy@gmail.com', 'nuua crkd nobq atwa', 'Azeem', '(855) 604-7215',None,None,None,None,None,'08857', 'QxXz7Wcmsv', 'Prescriber Specific - x'],
            # 'vojnyk, charlene': ['charlenevojnykmy','1December!', None, None, 'Azeem', '(833) 222-8313',None,None,'audreyramirez@mailbox.org','December092024!','charlenevojnykmy@mailbox.org','08857', '4RYe1Uyd63', 'Prescriber Specific - y'],
            # 'luo, hongxiu': ['hongxiuluomy','1December!', None, None, 'Azeem', '(866) 347-5049',None,None,'audreyramirez@mailbox.org','December092024!','hongxiuluomy@mailbox.org','08901', 'DTWRlFz3cO', 'Prescriber Specific - z'],
            # 'saavedra, ruben': ['rubensaavedrasc','1December!', None, None, 'Azeem', '(855) 631-0546',None,None,'audreyramirez@mailbox.org','December092024!','rubensaavedrasc@mailbox.org','11729', 'udJm3B5u4c', 'Prescriber Specific - aa'],
            # 'alluri, jagga': ['jaggaallurisc','1December!', None, None, 'Azeem', '(855) 661-5979',None,None,'audreyramirez@mailbox.org','December092024!','jaggaallurisc@mailbox.org','11375', '0zUVAzrZ47', 'Prescriber Specific - ab'],
            # 'katcher, oleg': ['olegkatchersc','1December!', None, None, 'Azeem', '(855) 710-6726',None,None,'audreyramirez@mailbox.org','December092024!','olegkatchersc@mailbox.org','11229', 'DIQjkkOnKW', 'Prescriber Specific - ac'],
            # 'coplan, jeremy': ['jeremycoplansc','1December!', None, None, 'Azeem', '(855) 710-7215',None,None,'audreyramirez@mailbox.org','December092024!','jeremycoplansc@mailbox.org','11030', 't4sGF1hkp7', 'Prescriber Specific - ad'],
            # 'hasan, zeeshan': ['zeeshanhasancr','1December!', None, None, 'Azeem', '(855) 881-3479',None,None,'audreyramirez@mailbox.org','December092024!','zeeshanhasancr@mailbox.org','11580', 'WA3441gB7p', 'Prescriber Specific - ae'],
            # 'raza, nadeem': ['razanadeemcres','1December!', None, None, 'Azeem', '(855) 859-6115',None,None,'audreyramirez@mailbox.org','December092024!','razanadeemcres@mailbox.org','11102', 'iQO31kab1T', 'Prescriber Specific - af'],
            # 'amey, jolanda': ['jolandaameycg','1December!', None, None, 'Azeem', '(855) 834-2008',None,None,'audreyramirez@mailbox.org','December092024!','jolandaameycg@mailbox.org','36527', 'oW1cbVyHLJ', 'Prescriber Specific - ag'],
            'fowler, emilie': ['emiliefowler', '1December!', None, None, 'Azeem','(833) 664-4123', 'EmilieFowlermed@outlook.com','https://hook.us1.make.com/52et885mcsd6rkodrurpyofumpiueszf',None,None,None,'10128','6ulCT4OitR', 'Prescriber Specific - y'],
            'nizam, mohammed': ['mohammednizammy','1December!', 'mohammednizammy@gmail.com', 'tifv wbew zrtc gfhb', 'Azeem', '(855) 631-0462',None,None,None,None,None,'10461', '5fiQdmeR7f', 'Prescriber Specific - z'],
            # 'padula, steven': ['stevenpadulart','1December!', None, None, 'Azeem', '(855) 748-4332',None,None,'stevenpadulart@mailbox.org','December092024!','stevenpadulart@mailbox.org','07440', '6XX4qAK9l7', 'Prescriber Specific - aa'],
            # 'geller, felix': ['felixgellerrt','1December!', None, None, 'Azeem', '(855) 543-5021',None,None,'stevenpadulart@mailbox.org','December092024!','felixgellerrt@mailbox.org','08755', 'MRhxwCT7ih', 'Prescriber Specific - ab'],
            # 'frances, moshe': ['moshefrancesrt','1December!', None, None, 'Azeem', '(855) 774-7418',None,None,'stevenpadulart@mailbox.org','December092024!','moshefrancesrt@mailbox.org','07712', 'DSyZpyZnGw', 'Prescriber Specific - ac'],
            # 'roman, jaime': ['jaimeroman77','1December!', None, None, 'Azeem', '(855) 863-1560',None,None,'stevenpadulart@mailbox.org','December092024!','Jaimeroman77@mailbox.org','11372', 'bLC6B6JeoY', 'Prescriber Specific - ad'],
            # 'gustin, gabriel': ['gabrielgustin77','1December!', None, None, 'Azeem', '(855) 724-7328',None,None,'stevenpadulart@mailbox.org','December092024!','gabrielgustin77@mailbox.org','11355', 'yxvRqRfcEZ', 'Prescriber Specific - ae'],
            # 'garcia, sonia': ['soniagarcia77','1December!', None, None, 'Azeem', '(855) 734-7418',None,None,'stevenpadulart@mailbox.org','December092024!','soniagarcia77@mailbox.org','11042', 'DQeWvtyc92', 'Prescriber Specific - af'],
            # 'buck, stephanie': ['stephaniebuck77','1December!', None, None, 'Azeem', '(855) 850-5377',None,None,'stevenpadulart@mailbox.org','December092024!','stephaniebuck77@mailbox.org','77380', 'PdEO7kjjjQ', 'Prescriber Specific - ag'],
            # 'baez abreu, jeisson': ['jeissonbaezrt','1December!', None, None, 'Azeem', '(855) 775-8536',None,None,'stevenpadulart@mailbox.org','December092024!','Jeissonbaezrt@mailbox.org','11373', 'DXreG30taI', 'Prescriber Specific - ah'],
            # 'siddiqui, saeed': ['seedsiddiquicr','1December!', None, None, 'Azeem', '(855) 821-4501',None,None,'stevenpadulart@mailbox.org','December092024!','seedsiddiquicr@mailbox.org','11570', 'N2U2LYQahp', 'Prescriber Specific - ai'],
            # 'farooqi, mushahid': ['farooqimushahidcr','1December!', None, None, 'Azeem', '(855) 859-0279',None,None,'stevenpadulart@mailbox.org','December092024!','farooqimushahidcr@mailbox.org','11418', 'rlIzyXnCwk', 'Prescriber Specific - aj'],
            # 'hamid, faisal': ['hamidfaisalcr','1December!', None, None, 'Azeem', '(855) 850-5377',None,None,'stevenpadulart@mailbox.org','December092024!','hamidfaisalcr@mailbox.org','11580', 'IHjfqakQaD', 'Prescriber Specific - ak'],
            'powell, michelle': ['michellepowellcg','1December!', None, None, 'Azeem', '(855) 884-4569',None,None,'michellepowellcg@mailbox.org','December092024!','michellepowellcg@mailbox.org','33133', 'I8wtnIgVG3', 'Prescriber Specific - aa'],
            'vukic, mario': ['mariovukic506','1March!!!', 'mariovukic506@gmail.com', 'lqub hefx pqei pjtw', 'Azeem', '(201) 734-6192',None,None,None,None,None,'07601', '11alipjtw', 'Prescriber Specific - ab'],
            'rojas, milagros': ['milagrosrojas5520','1March!!!', 'milagrosrojas5520@gmail.com', 'tsya omwf ijsl jycm', 'Azeem', '(609) 710-0518',None,None,None,None,None,'07424', '11alijycm', 'Prescriber Specific - ac'],
            'jafri, syed': ['syedjafrielix','1December!', None, None, 'Azeem', '(908) 450-1232',None,None,'kathleencarstens@mailbox.org','December092024!','syedjafrielix@mailbox.org','77030', 'k1sWngDZYG', 'Prescriber Specific - ad'],
            'ali, shaik': ['shaikaliwh','1December!', 'shaikaliwh@gmail.com', 'oean lpgy zseb mgfh', 'Azeem', '(732) 362-4710',None,None,None,None,None,'11419', '11alimgfh', 'Prescriber Specific - ae'],
            'wilson-tarpeh, ellen': ['ellenwilsonwh','1December!', 'ellenwilsonwh@gmail.com', 'twel ztpg yhze vxmb', 'Azeem', '(856) 409-0417',None,None,None,None,None,'08103', '11wilsonvxmb', 'Prescriber Specific - af'],
            'brown, dwayne': ['dwaynebrownmd','1December!', 'dwaynebrownmd@gmail.com', 'wuds tkok yxxf pcar', 'Azeem', '(833) 523-2317',None,None,None,None,None,'06510', '11brownpcar', 'Prescriber Specific - ag'],
            'schlakman, brandon': ['schlakmanbrandonwh','1December!', 'schlakmanbrandonwh@gmail.com', 'osja ncey yfkn nizg', 'Azeem', '(856) 644-4625',None,None,None,None,None,'08080', '11schlakmannizg', 'Prescriber Specific - ah'],
            'friedberg, andrea': ['andreafriedburgwh','1December!', 'andreafriedburgwh@gmail.com', 'lzzz pyot yfvz qvcg', 'Azeem', '(848) 260-6463',None,None,None,None,None,'08096', '11friedbergqvcg', 'Prescriber Specific - ai'],
            'mellul, david': ['davidmellulwh','1December!', 'davidmellulwh@gmail.com', 'xjgl afbl zpnp vple', 'Azeem', '(848) 260-3767',None,None,None,None,None,'08034', '11mellulvple', 'Prescriber Specific - aj'],
            'weinstock, brett': ['brettweinstockwh','1December!', 'brettweinstockwh@gmail.com', 'ucvp yifz fgji riuf', 'Azeem', '(848) 260-3071',None,None,None,None,None,'08096', '11weinstockriuf', 'Prescriber Specific - ak'],
            'rosenfeld, deborah': ['deborahrosenfeldwh','1December!', 'deborahrosenfeldwh@gmail.com', 'hdja fwsk umxa msxr', 'Azeem', '(732) 527-3089',None,None,None,None,None,'08053', '11rosenfeldmsxr', 'Prescriber Specific - al'],
            'wuzzardo, brandon': ['brandonwuzzardowh','1December!', 'brandonwuzzardowh@gmail.com', 'wask itae njvy daxw', 'Azeem', '(862) 772-1121',None,None,None,None,None,'08302', '11wuzzardodaxw', 'Prescriber Specific - am'],
            'florio suskevic, katherine': ['katherinefloriowh','1December!', 'katherinefloriowh@gmail.com', 'ohml pdif fwos xzof', 'Azeem', '(609) 256-4050',None,None,None,None,None,'07726', '11floriozxof', 'Prescriber Specific - an'],
            'mcnally, kristie': ['krstiemcnallywh','1December!', 'krstiemcnallywh@gmail.com', 'eqpv evpf tjyp cfvp', 'Azeem', '(848) 260-6607',None,None,None,None,None,'08053', '11mcnallycfvp', 'Prescriber Specific - ao'],
            'patel, pradip': ['pardippatelwh','1December!', 'pardippatelwh@gmail.com', 'ogie tdbl glhd vhea', 'Azeem', '(609) 318-3050',None,None,None,None,None,'08021', '11pateloqpy', 'Prescriber Specific - ap'],
            'pintauro, kellyann': ['kellyannpintauromp','1December!', 'kellyannpintauromp@gmail.com', 'jeij xrgm oddz grxe', 'Azeem', '(212) 658-9753',None,None,None,None,None,'10469', '11pintaurogrxe', 'Prescriber Specific - aq'],
            'parikh, haley': ['haleyparikhwh','1December!', 'haleyparikhwh@gmail.com', 'gwcb wmgm wteo busa', 'Azeem', '(862) 290-3926',None,None,None,None,None,'08053', '11parikhbusa', 'Prescriber Specific - ar'],
            'tran, jacques': ['tranjacqueswh','1December!', 'tranjacqueswh@gmail.com', 'ncgx plbc cedv ostl', 'Azeem', '(848) 994-4295',None,None,None,None,None,'08034', '11tranostl', 'Prescriber Specific - as'],
            'yu, may': ['mayyumpp','1December!', 'mayyumpp@gmail.com', 'dvsf hsbm yovt ltue', 'Azeem', '(716) 433-3769',None,None,None,None,None,'11372', '11yumayltue', 'Prescriber Specific - at'],
            'cruz, taisha': ['taishacruzmpp','1December!', 'taishacruzmpp@gmail.com', 'oghm hbkd akis tecl', 'Azeem', '(718) 691-4539',None,None,None,None,None,'10033', '11cruztecl', 'Prescriber Specific - au'],
            'pintauro, robert': ['robertpintauromp','1December!', 'robertpintauromp@gmail.com', 'qwtq krjt zmyv fzbl', 'Azeem', '(347) 708-4822',None,None,None,None,None,'10461', '11pintaurofzbl', 'Prescriber Specific - av'],
            'som, sumit': ['sumitsomfc','1December!', 'sumitsomfc@gmail.com', 'fmjl lnze zhbl aqwr', 'Azeem', '(973) 658-4171',None,None,None,None,None,'47129', '11somaqwr', 'Prescriber Specific - aw'],
            'humera, rafath': ['rafathhumerafc','1December!', 'rafathhumerafc@gmail.com', 'rcbw sywv fgcs gudd', 'Azeem', '(732) 362-4607',None,None,None,None,None,'07011', '11humeragudd', 'Prescriber Specific - ax'],
            'szymanek, erica': ['ericaszymanekfc','1December!', 'ericaszymanekfc@gmail.com', 'tsxa lmgz ojoc bvuc', 'Azeem', '(862) 799-3705',None,None,None,None,None,'07702', '11szymanekbvuc', 'Prescriber Specific - ay'],
            'khan, intazam': ['khanintzamrp','1December!', 'khanintzamrp@gmail.com', 'wtme bosz xamz nlyl', 'Azeem', '(718) 691-4517',None,None,None,None,None,'11102', '11khannlyl', 'Prescriber Specific - az'],
            'moeller, chaim': ['chaimmoellerr','1December!', 'chaimmoellerr@gmail.com', 'bstk xljh dlor lbyq', 'Azeem', '(212) 981-3705',None,None,None,None,None,'11415', '11chaimlbyq', 'Prescriber Specific - ba'],
            'ilyayeva, stella': ['stellailyayevar','1December!', 'stellailyayevar@gmail.com', 'ijrt edeg klav gtyl', 'Azeem', '(718) 691-4560',None,None,None,None,None,'11374', '11ilyayevagtyl', 'Prescriber Specific - bb'],
            'izrayelit, leonid': ['leonidizrayelitr','1December!', 'leonidizrayelitr@gmail.com', 'rave vvna ekbz jhlx', 'Azeem', '(718) 691-4530',None,None,None,None,None,'11375', '11izrayelitjhlx', 'Prescriber Specific - bc'],
            'fashakin, emmanuel': ['emmanuelfashakinr','1December!', 'emmanuelfashakinr@gmail.com', 'ugsh ldoj cyqt ewkw', 'Azeem', '(718) 691-4537',None,None,None,None,None,'11207', '11fashakinewkw', 'Prescriber Specific - bd'],
            'mannan, bilal': ['bilalmannanem','1December!', 'bilalmannanem@gmail.com', 'ytdr trbo whlh reyi', 'Azeem', '(610) 269-4007',None,None,None,None,None,'19317', '11mannanreyi', 'Prescriber Specific - be'],
            'bognet, joseph': ['josephbognetem','1December!', 'josephbognetem@gmail.com', 'jfyu roxd fsfw subl', 'Azeem', '(607) 304-9472',None,None,None,None,None,'18103', '11bognetsubl', 'Prescriber Specific - bf'],
            'westgate, danielle': ['daniellewestgateem','1December!', 'daniellewestgateem@gmail.com', 'lcod piwu ghyr yfae', 'Azeem', '(717) 389-4675',None,None,None,None,None,'18103', '11westgateyfae', 'Prescriber Specific - bg'],
            'romascavage, frank': ['romascavgefrankem','1December!', 'romascavgefrankem@gmail.com', 'hxqm ypci udbl twlh', 'Azeem', '(570) 300-1752',None,None,None,None,None,'18337', '11romascavagetwlh', 'Prescriber Specific - bh'],
            'kaufman, kathy': ['kathykaufmanem','1December!', 'kathykaufmanem@gmail.com', 'xdlk dxvy oiml xqst', 'Azeem', '(570) 871-0900',None,None,None,None,None,'18049', '11kaufmanxqst', 'Prescriber Specific - bi'],
            'swartz, stephen': ['swartzstephenm','1December!', 'swartzstephenm@gmail.com', 'ftwo yqjy zlbs ifuk', 'Azeem', '(914) 265-8797',None,None,None,None,None,'07733', '11swartzifuk', 'Prescriber Specific - bj'],
            'mazzocchi, dominic': ['mozzocchidominicm','1December!', 'mozzocchidominicm@gmail.com', 'jepz dazo dfgw ppqd', 'Azeem', '(732) 527-3098',None,None,None,None,None,'08742', '11mazzocchippqd', 'Prescriber Specific - bk'],
            'van der sluis, ralf': ['vanderralfm','1December!', 'vanderralfm@gmail.com', 'gtro pmgo esbk dtjl', 'Azeem', '(609) 225-5184',None,None,None,None,None,'08244', '11vanderdtjl', 'Prescriber Specific - bl'],
            'movva, srinivasa': ['srinivasamovvam','1December!', 'srinivasamovvam@gmail.com', 'tynn rnva nylg sugs', 'Azeem', '(732) 694-7072',None,None,None,None,None,'07716', '11movasugs', 'Prescriber Specific - bm'],
            # 'bhargava, pooja': ['poojabhargava081','1December!', 'poojabhargava081@gmail.com', 'wiot ciqq tjof qmoc', 'Azeem', '(908) 450-1649',None,None,None,None,None,'07036', '11movaqmoc', 'Prescriber Specific - by'],
            'bozzi, meredith': ['meredithbozzi','12Feb!!!', 'meredithbozzi57@gmail.com', 'gzzo izke rzbu rmhn', 'Azeem', '(862) 772-1875',None,None,None,None,None,'08053', '11movagpdn', 'Prescriber Specific - bn'],
            # 'mohanrao, shailender': ['shailendermohanrao','1December!', 'shailendermohanrao@gmail.com', 'wdcj yirm dolx ebvx', 'Azeem', '(908) 450-1740',None,None,None,None,None,'07079', '11movaebvx', 'Prescriber Specific - cj'],
            'demarco, lauren': ['laurendemarco','12Feb!!!', 'laurendemarco51@gmail.com', 'usid ifvb vvql ubxb', 'Azeem', '(908) 718-7306',None,None,None,None,None,'10065', '11movatrah', 'Prescriber Specific - bo'],
            'bijal, dave': ['davebilaj','1December!', 'davebilaj@gmail.com', 'mbmm aewj fnco hvkn', 'Azeem', '(908) 914-0459',None,None,None,None,None,'07840', '11movahvkn', 'Prescriber Specific - bp'],
            'maykish, susan': ['maykishsusan','1December!', 'maykishsusan@gmail.com', 'sglg rfyd ouig ufgo', 'Azeem', '(908) 441-5919',None,None,None,None,None,'07960', '11movaufgo', 'Prescriber Specific - bq'],
            'khesin, yevgeniy': ['yevgeniykhesin5','1December!', 'yevgeniykhesin5@gmail.com', 'riox oalx ubij nxuj', 'Azeem', '(908) 450-1488',None,None,None,None,None,'07860', '11movanxuj', 'Prescriber Specific - br'],
            # 'cantillon, marc': ['marccantillon99','1December!', 'marccantillon99@gmail.com', 'tyfd fzwe buub gwca', 'Azeem', '(908) 914-0455',None,None,None,None,None,'07036', '11movagwca', 'Prescriber Specific - co'],
            # 'ezzi, nisreen': ['ezzinisreen70','1December!', 'ezzinisreen70@gmail.com', 'nxds jeny nlyg drpy', 'Azeem', '(516) 706-8855',None,None,None,None,None,'11801', '11movadrpy', 'Prescriber Specific - cp'], 
            'alemu, ermiyas': ['alemuermiyas245','1December!', 'alemuermiyas245@gmail.com', 'gjpx ezxj jiqy jbyh', 'Azeem', '(716) 218-4352',None,None,None,None,None,'10451', '11movajbyh', 'Prescriber Specific - bs'], 
            'chi, danny': ['chidanny909','1December!', 'chidanny909@gmail.com', 'evxr vouy grqa pqac', 'Azeem', '(518) 677-1835',None,None,None,None,None,'11234', '11movapqac', 'Prescriber Specific - bt'], 
            'morgan, dorcas': ['dorcasmorganl33','1December!', 'dorcasmorganl33@gmail.com', 'pmdj tthm ozid ymep', 'Azeem', '(646) 844-7489',None,None,None,None,None,'10462', '11movaymep', 'Prescriber Specific - bu'],
            'belman, anna': ['annabeman255','1December!', 'annabeman255@gmail.com', 'uggt humw rmfq cjoz', 'Azeem', '(929) 335-7997',None,None,None,None,None,'06902', '11movacjoz', 'Prescriber Specific - bv'],  
            # 'buka, robert': ['robertbuka000','1December!', 'robertbuka000@gmail.com', 'cqvp jgbt pypc wsgo', 'Azeem', '(212) 658-9886',None,None,None,None,None,'10038', '11movawsgo', 'Prescriber Specific - cu'],
            'enuma, celestina': ['celestinaenuma59','1December!', 'celestinaenuma59@gmail.com', 'jvjy etdx fuvy tmii', 'Azeem', '(908) 450-1355',None,None,None,None,None,'07060', '11movatmii', 'Prescriber Specific - bw'],
            'cervone, joseph': ['josephcervone727','1December!', 'josephcervone727@gmail.com', 'sspp cbdz myuj rfsq', 'Azeem', '(908) 450-1739',None,None,None,None,None,'07052', '11movarfsq', 'Prescriber Specific - bx'],
            'kochhar, rikhil': ['rikhilkochhar29','1December!', 'rikhilkochhar29@gmail.com', 'wabw xxke aurl bkeu', 'Azeem', '(718) 691-4551',None,None,None,None,None,'10458', '11movabkeu', 'Prescriber Specific - by'],  
            # 'kilgore, kortni': ['kortnikilgorep','1December!', 'kortnikilgorep@gmail.com', 'wxhs ojsj ippx kpqi', 'Azeem', '(718) 691-4482',None,None,None,None,None,'30180', '11movakqpi', 'Prescriber Specific - cy'],
            'lira, lorraine': ['lorrainelira0025','1March!!!', 'lorrainelira0025@gmail.com', 'vdsh mzmp qfoh kswm', 'Azeem', '(201) 589-2260',None,None,None,None,None,'07675', '11movakswm', 'Prescriber Specific - bz'],
            'vitale, joseph': ['josephvitale285','1March!!!', 'josephvitale285@gmail.com', 'oueg gphh chge baua', 'Azeem', '(908) 450-1251',None,None,None,None,None,'07424', '11movabuqx', 'Prescriber Specific - ca'],
            'fellus, jonathan': ['jonathanfellus046','1March!!!', 'jonathanfellus046@gmail.com', 'huej mysz psew buqx', 'Azeem', '(908) 452-6979',None,None,None,None,None,'07836', '11movabuqx', 'Prescriber Specific - cb'],
            # 'gupta, deepali': ['deepaligupta0010','1March!!!', 'deepaligupta0010@gmail.com', 'nwsv ssxt igrz hhtc', 'Azeem', '(718) 691-4432',None,None,None,None,None,'11209', '11movahhtc', 'Prescriber Specific - co'],
            'rapadas, cathryn': ['cathrynrapadas538','1March!!!', 'cathrynrapadas538@gmail.com', 'tvra dodb shbm dotz', 'Azeem', '(908) 450-1773',None,None,None,None,None,'07503', '11movadotz', 'Prescriber Specific - cc'],
            # 'miric, slobodan': ['slobodanmiric001','1March!!!', 'slobodanmiric001@gmail.com', 'pmed laln tkad kngq', 'Azeem', '(201) 734-6167',None,None,None,None,None,'07843', '11movakngq', 'Prescriber Specific - de'],
            'haghverdi, mojdeh': ['mojdehhaghverdi','1March!!!', 'mojdehhaghverdi@gmail.com', 'lbqn alaj ztfg hkjx', 'Azeem', '(908) 378-1619',None,None,None,None,None,'07424', '11movahkjx', 'Prescriber Specific - cd'],
            'marquinez, anthony': ['anthonymarquinez004','1March!!!', 'anthonymarquinez004@gmail.com', 'mngd xytu apwi odwh', 'Azeem', '(201) 735-7701',None,None,None,None,None,'07601', '11movakqpi', 'Prescriber Specific - ce'],
            'cadesky, adam': ['cadeskya','1December!', 'cadeskya@gmail.com', 'oxvo nqps dcyg vkds', 'Azeem', '(718) 691-4512',None,None,None,None,None,'10453', '11movavkds', 'Prescriber Specific - cf'],
            'kapoor, anil': ['kapooranilp','1March!!!', 'kapooranilp@gmail.com', 'qyuc bgcc lncs aorh', 'Azeem', '(718) 691-4458',None,None,None,None,None,'11373', '11movaaorh', 'Prescriber Specific - cg'],
            'pildysh, inna': ['innapildyshp','1March!!!', 'innapildyshp@gmail.com', 'vnuw fkfs gjyl xesd', 'Azeem', '(718) 691-4472',None,None,None,None,None,'11204', '11movaxesd', 'Prescriber Specific - ch'],
            'siddiqui, anila': ['anilasiddiquip','1March!!!', 'anilasiddiquip@gmail.com', 'jenb cnmw wtvz ghps', 'Azeem', '(516) 717-2988',None,None,None,None,None,'11554', '11movaghps', 'Prescriber Specific - ci'],
            # 'hersh, judith': ['judithhershp','1March!!!', 'judithhershp@gmail.com', 'urtg jkux yjrc yfzj', 'Azeem', '(908) 378-1664',None,None,None,None,None,'07016', '11movayfzj', 'Prescriber Specific - dl'],
            # 'khan, dewan': ['dewankhanpl','1March!!!', 'dewankhanpl@gmail.com', 'jxoj lymt frxl aspr', 'Azeem', '(908) 378-1686',None,None,None,None,None,'08861', '11movaaspr', 'Prescriber Specific - dm'],
            'sammartino, robert': ['robertsammartinop','1March!!!', 'robertsammartinop@gmail.com', 'umuw pdxx cluq otle', 'Azeem', '(856) 581-8935',None,None,None,None,None,'08080', '11movaotle', 'Prescriber Specific - cj'],
            'jing, tong': ['tongjingelix','1March!!!', 'tongjingelix@gmail.com', 'nvbk qsgd sjzk juoq', 'Azeem', '(718) 691-4462',None,None,None,None,None,'11354', '11movajuoq', 'Prescriber Specific - ck'],
            'hitchner, allison': ['allisonhitchnerp','1March!!!', 'allisonhitchnerp@gmail.com', 'kuhu uvsh noki dthx', 'Azeem', '(908) 914-0479',None,None,None,None,None,'08050', '11movadthx', 'Prescriber Specific - cl'],
            'hyun, jae': ['jaegeunhyun02','1December!', 'jaegeunhyun02@gmail.com', 'hudg jtlk utoz ahdn', 'Azeem', '(201) 477-0872',None,None,None,None,None,'07631', '11movaahdn', 'Prescriber Specific - cm'],
            'hyun, jae geun': ['jaegeunhyun02','1December!', 'jaegeunhyun02@gmail.com', 'hudg jtlk utoz ahdn', 'Azeem', '(201) 477-0872',None,None,None,None,None,'07631', '11movaahdn', 'Prescriber Specific - cm'],
            'tan, wu': ['wutanler','1March!!!', 'wutanler@gmail.com', 'kaqm otgw bfgg aqbt', 'Azeem', '(347) 745-3932',None,None,None,None,None,'11355', '11movaaqbt', 'Prescriber Specific - cn'],
            'peters, dana': ['danapetersel','1March!!!', 'danapetersel@gmail.com', 'xsno ahcv ortm llia', 'Azeem', '(908) 300-3744',None,None,None,None,None,'08701', '11movallia', 'Prescriber Specific - co'],
            'solaimanzadeh, sima': ['simasolaimanzadeh339','12Feb!!!', 'simasolaimanzadeh339@gmail.com', 'muty wuyo coql zeva', 'Azeem', '(908) 272-5994',None,None,None,None,None,'07080', '11movanjdk', 'Prescriber Specific - cp'],
            'noor, emad': ['nooremadp','12Feb!!!', 'nooremadp@gmail.com', 'yqfy byck lldv kshs', 'Azeem', '(732) 523-4064',None,None,None,None,None,'08820', '11movanjdk', 'Prescriber Specific - cq'],
            'leone, matthew': ['matthewsLeone','12Feb!!!', 'matthewsleone23@gmail.com', 'tpmj wzxm ivzq dkhe', 'Azeem', '(845) 653-3477',None,None,None,None,None,'12550', '11movanjdk', 'Prescriber Specific - cr'],            
            'mikolaenko, ivan': ['ivanmikolaenkop','12Feb!!!', 'ivanmikolaenkop@gmail.com', 'sptz qlvu qxdf kivv', 'Azeem', '(516) 387-9890',None,None,None,None,None,'11570', '11movanjdk', 'Prescriber Specific - cs'],
            'saw, thazin': ['thazinsaw','1December!', 'thazinsaw135@gmail.com', 'qzyk gpzr cxhr lspa', 'Azeem', '(716) 322-2565',None,None,None,None,None,'11201', '11movanjdk', 'Prescriber Specific - ct'],
            # 'tihomirovs, nadejda': ['nadejdatihomirov','12Feb!!!', 'nadejdatihomirovs49@gmail.com', 'beqw ltfq hyvf tdms', 'Azeem', '(917) 464-1687',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - dy'],
            # 'schwartz, marlan': ['Schwartztricounty','Yankees@2025', 'Schwartz.tricounty@gmail.com', 'bble flyd nnpd wsqy', 'Azeem', '(609) 498-7254',None,None,None,None,None,'08854', '11movanjdk', 'Prescriber Specific - dz'],
            'antebi, yael': ['yaelantebi3','12Feb!!!', 'yaelantebi3@gmail.com', 'tkdn razn wcpu nmrb', 'Azeem', '(973) 472-5433',None,None,None,None,None,'07052', '11movanjdk', 'Prescriber Specific - cu'],
            'korogluyev, mikhail': ['mikhailyuryevichkorogluyevs','12Feb!!!', 'mikhailyuryevichkorogluyev@gmail.com', 'xlxf xinz blyo ksua', 'Azeem', '(917) 677-6610',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - cv'],
            # 'korogluyev, mikhail': ['Pahamiltongi','ADH0ne4all!', 'hamiltongi.pa@gmail.com', 'wnik zpox ctuy bjts', 'Azeem', '(917) 677-6610',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - eb'],
            'kremen, inna': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - cw'],
            'gupta, manjari': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - cx'],
            'owunna, uzoma': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - cy'],
            'gross, renee': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - cz'],
            'gleason, abigail': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - da'],
            'brown, jennifer': ['ebobgynpa','EastBrunswick1234!', 'ebobgyn.pa@gmail.com', 'gtns gaxk iwuf lxcq', 'Azeem', '(732) 254-1436',None,None,None,None,None,'11235', '11movanjdk', 'Prescriber Specific - db'],
            'tung, william': ['williamtung','12Feb!!!', 'williamtung37@gmail.com', 'zsqs diwx rrtt izcm', 'Azeem', '(678) 530-1193',None,None,None,None,None,'30135', '11movanjdk', 'Prescriber Specific - dc'],
            'nieves, jessica': ['jessicanieves','12Feb!!!', 'jessicaleannnieves@gmail.com', 'wnga hkwx vsjb xvkd', 'Azeem', '(770) 216-1629',None,None,None,None,None,'30281', '11movatxsd', 'Prescriber Specific - dd'],
            'schuler, anna': ['Annaschuler','12Feb!!!', 'annaschuler270@gmail.com', 'xwwu flok qqum wven', 'Azeem', '(678) 623-3178',None,None,None,None,None,'30106', '11movacjym', 'Prescriber Specific - de'],
            'hussaini, batool': ['Batoolhussaini','12Feb!!!', 'batoolhussainif@gmail.com', 'pudf uxcu tplt gpwf', 'Azeem', '(718) 691-4405',None,None,None,None,None,'11418', '11movanjdk', 'Prescriber Specific - df'],
            'escobar, paola': ['paolaescobarp','12Feb!!!', 'holisticobgynmidw@gmail.com', 'vgkc ovit fukq vdwq', 'Azeem', '(908) 378-7754',None,None,None,None,None,'07016', '11movanjdk', 'Prescriber Specific - dg'],
            'frenkel, violina': ['integrativebehavirlcare','12Feb!!!', 'integrativebehavirlcare@gmail.com', 'lvay svik hfsw lstx', 'Azeem', '(908) 378-1639',None,None,None,None,None,'07920', '11movanjdk', 'Prescriber Specific - dh'],
            'shahid, haroon': ['revealweightloss','12Feb!!!', 'revealweightloss2@gmail.com', 'awhs ikko esat kuch', 'Azeem', '(551) 237-8030',None,None,None,None,None,'07036', '11movanjdk', 'Prescriber Specific - di'],
            # 'osman, khaled': ['khaledosmanfd','12Feb!!!', 'khaledosmanfd@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(718) 691-4398',None,None,None,None,None,'11229', '11movanjdk', 'Prescriber Specific - dg'],




            # 'md, matthew': ['matthewsmarksp','1March!!!', 'matthewsmarksp@gmail.com', 'vvjl ybjy rnae crjc', 'Azeem', '(212) 658-9754',None,None,None,None,None,'07079', '11movacrjc', 'Prescriber Specific - du'],
            # 'rajapakse, john': ['johnrajapaksep','1March!!!', 'johnrajapaksep@gmail.com', 'votv crdh xfel mzlw', 'Azeem', '(908) 450-1325',None,None,None,None,None,'07079', '11movamzlw', 'Prescriber Specific - dv'],
            # 'gulevski, vasko': ['vaskogulevskip','1March!!!', 'vaskogulevskip@gmail.com', 'wfyl ljrx dbki kurr', 'Azeem', '(908) 378-1811',None,None,None,None,None,'07079', '11movakurr', 'Prescriber Specific - dw'],
            # 'gialanella, francis': ['francisgialanellap','1March!!!', 'francisgialanellap@gmail.com', 'taft fenm hyam owta', 'Azeem', '(908) 378-1647',None,None,None,None,None,'07079', '11movaowta', 'Prescriber Specific - dx'],
            # 'klenofsky, britany': ['britanyklenofskyp','1March!!!', 'britanyklenofskyp@gmail.com', 'qech bzvn dlbs hnbo', 'Azeem', '(718) 691-4430',None,None,None,None,None,'07079', '11movahnbo', 'Prescriber Specific - dy'],
            # 'persaud, lisa': ['lisapersaudp','1March!!!', 'lisapersaudp@gmail.com', 'mijl nmrs ejyn swii', 'Azeem', '(516) 710-7201',None,None,None,None,None,'07079', '11movaswii', 'Prescriber Specific - ea'],
            # 'persaud, devicka': ['devickapersaudp','1March!!!', 'devickapersaudp@gmail.com', 'tcgo cfxq wmcf xnyk', 'Azeem', '(718) 691-4553',None,None,None,None,None,'07079', '11movaxnyk', 'Prescriber Specific - eb'],
            # 'li, lixuan': ['lixuanlip','1March!!!', 'lixuanlip@gmail.com', 'pqdu zevz jytm tsru', 'Azeem', '(212) 658-9498',None,None,None,None,None,'07079', '11movatsru', 'Prescriber Specific - ec'],
            # 'wellner, murray': ['murraywellnerp','1March!!!', 'murraywellnerp@gmail.com', 'zjyg acfm ubnm aoss', 'Azeem', '(959) 212-6098',None,None,None,None,None,'07079', '11movaaoss', 'Prescriber Specific - ed'],
            # 'roy, nita': ['roynitap','1March!!!', 'roynitap@gmail.com', 'jbnu aejr clat sqgr', 'Azeem', '(718) 691-4473',None,None,None,None,None,'07079', '11movasqgr', 'Prescriber Specific - ee'],
            # 'schuler, anna': ['annaschulerp','1March!!!', 'annaschulerp@gmail.com', 'fnzu shdq njcu cjym', 'Azeem', '(770) 216-1733',None,None,None,None,None,'07079', '11movacjym', 'Prescriber Specific - ef'],
            # 'mei, xiaoyang': ['xiaoyangmeip','1March!!!', 'xiaoyangmeip@gmail.com', 'xzch zhfc kayw fscz', 'Azeem', '(212) 658-9733',None,None,None,None,None,'07079', '11movafscz', 'Prescriber Specific - eg'],
            # 'swan, alexander': ['Alexanderswanp','1March!!!', 'Alexanderswanp@gmail.com', 'qjnm iswd mytg ouxj', 'Azeem', '(908) 378-1815',None,None,None,None,None,'07079', '11movaouxj', 'Prescriber Specific - eh'],
            # 'dixit, seema': ['Seemadixitp','1March!!!', 'Seemadixitp@gmail.com', 'tnva ebaq jxdg wqfh', 'Azeem', '(908) 378-1688',None,None,None,None,None,'07079', '11movawqfh', 'Prescriber Specific - ei'],
            # 'platovsky, anna': ['annaplatovskyp','1March!!!', 'annaplatovskyp@gmail.com', 'hiqh wipx kajy ucde', 'Azeem', '(908) 378-1670',None,None,None,None,None,'07079', '11movaucde', 'Prescriber Specific - ej'],
            # 'patel, himanshu': ['patelhimanshuf','1March!!!', 'patelhimanshuf@gmail.com', 'wksv conm yyao qmlw', 'Azeem', '(908) 378-1625',None,None,None,None,None,'07079', '11movaqmlw', 'Prescriber Specific - ek'],
            # 'temitope, adeyeye': ['temitopeadeyex','1December!', 'temitopeadeyeyex@gmail.com', 'hbuv ydrk hnxk dnzm', 'Azeem', '(470) 440-2469',None,None,None,None,None,'07079', '11movadnzm', 'Prescriber Specific - el'],
            # 'phillips, chloe': ['chloephillipsd','1March!!!', 'chloephillipsd@gmail.com', 'xuxc jome grrz xkxt', 'Azeem', '(908) 378-1643',None,None,None,None,None,'07079', '11movaxkxt', 'Prescriber Specific - em'],
            # 'mittman, robert': ['robertmittmanu','1March!!!', 'robertmittmanu@gmail.com', 'drle uior yhon dhmc', 'Azeem', '(718) 691-4564',None,None,None,None,None,'07079', '11movadhmc', 'Prescriber Specific - en'],
            # 'milgram, irina': ['irinamilgramc','1March!!!', 'irinamilgramc@gmail.com', 'ptoj veft askt gxkz', 'Azeem', '(908) 378-7651',None,None,None,None,None,'07079', '11movagxkz', 'Prescriber Specific - eo'],
            # 'wiener, craig': ['craigwienerj','1March!!!', 'craigwienerj@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(201) 734-6109',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - ep'],
            # 'sticco, christine': ['christinesticcow','1March!!!', 'christinesticcow@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(908) 378-7674',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - eq'],
            # 'rubino, robert': ['robertrubinoq','1March!!!', 'robertrubinoq@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(908) 378-1699',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - er'],
            # 'silverstein, michael p': ['michaelpsilversteinrr','1March!!!', 'michaelpsilversteinr@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(201) 643-2406',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - es'],
            # 'tung, william': ['tungwilliamp','1March!!!', 'tungwilliamp@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(678) 840-3993',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - et'],
            # 'honore, lesly': ['leslyhonorep','1March!!!', 'leslyhonorep@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(516) 717-3614',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - eu'],
            # 'nagaria, zain': ['zainnagaria','1March!!!', 'zainnagaria@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(201) 643-2439',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - ev'],
            # 'hall, reginald': ['reginaldhallf','1March!!!', 'reginaldhallf@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(470) 407-4735',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - ew'],
            # 'korogluyev, mikhail': ['mikhailkorogluyevj','1March!!!', 'mikhailkorogluyevj@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(718) 691-4425',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - ex'],
            # 'rozehzadeh, rabin': ['Rabinrozehzadehj','1March!!!', 'Rabinrozehzadehj@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(908) 378-1816',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - ey'],
            # 'ouyang, haoxu': ['haoxuouyangk','1March!!!', 'haoxuouyangk@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(718) 691-4419',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - ez'],
            # 'farooki, mansoor': ['mansoorfarookit','1March!!!', 'mansoorfarookit@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(716) 676-5570',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - fb'],
            # 'zitser, gene': ['genezitser36','1March!!!', 'genezitser36@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(716) 303-7628',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - fc'],
            # 'naqvi, syed': ['syedhnaqvik','1March!!!', 'syedhnaqvik@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(716) 408-5552',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - fd'],
            # 'fayyaz, tooba': ['toobafayyaz4','1March!!!', 'toobafayyaz4@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(862) 367-8285',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - ff'],
            # 'tenembaum, david': ['davidtenembaump','1March!!!', 'davidtenembaump@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(716) 303-7627',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - fg'],
            # 'mashettiwar, javi': ['javiamashettiwar','1March!!!', 'javiamashettiwar@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(908) 378-7698',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - fh'],
            # 'siegel, sheera': ['siegelsheera','1March!!!', 'siegelsheera@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(908) 378-7720',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - fi'],
            # 'campos, karina': ['karinacamposfd','1March!!!', 'karinacamposfd@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(908) 378-7641',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - fj'],
            # 'patel, rakhee': ['patelrakhee03','1March!!!', 'patelrakhee03@gmail.com', 'prou omok tzyl njdk', 'Azeem', '(201) 643-2408',None,None,None,None,None,'07079', '11movanjdk', 'Prescriber Specific - fk'],

        } 


names = [
    "mei, xiaoyang",
    "gulevski, vasko",
    "mohanrao, shailender",
    "persaud, devicka",
    "rajapakse, john",
    "sticco, christine",
    "rubino, robert",
    "silverstein, michael p",
    "tung, william",
    "honore, lesly",
    "nagaria, zain",
    "hall, reginald",
    "korogluyev, mikhail",
    "rozehzadeh, rabin",
    "ouyang, haoxu",
    "osman, khaled",
    "farooki, mansoor",
    "zitser, gene",
    "naqvi, syed",
    "hussaini, batool",
    "fayyaz, tooba",
    "tenembaum, david",
    "mashettiwar, javi",
    "siegel, sheera",
    "campos, karina",
    "patel, rakhee",
    "temitope, adeyeye",
    "phillips, chloe",
    "mittman, robert",
    "milgram, irina",
    "wiener, craig",
    "patel, himanshu",
    "platovsky, anna",
    "dixit, seema",
    "swan, alexander",
    "schuler, anna",
    "roy, nita",
    "wellner, murray",
    "li, lixuan",
    "persaud, lisa",
    "nieves, jessica",
    "klenofsky, britany",
    "gialanella, francis",
    "md, matthew"
]  

